 
apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: application
  lifecycle: production
  owner: user:guest
metadata:
  name: "${{ values.componentId }}"
  labels:
    app.kubernetes.io/name: "${{ values.componentId }}"
    app.kubernetes.io/version: "${{ values.version }}"
    app.quarkus.io/version: 3.18.3
  annotations:
    backstage.io/source-location: "url:https://${{ values.repoHost }}/${{ values.repoOrg }}/${{ values.repoName }}"
  tags:
  - java
  - quarkus
