 |
  
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      app.quarkus.io/quarkus-version: 3.18.3
      app.quarkus.io/commit-id: c708e59c9760a922c4a2b1a73ee3b21d1ffc6f4a
      app.quarkus.io/vcs-uri: https://github.com/iocanel/${{ values.componentId }}.git
      app.quarkus.io/build-timestamp: 2025-04-08 - 12:38:31 +0000
    labels:
      app.kubernetes.io/name: ${{ values.componentId }}
      app.kubernetes.io/version: ${{ values.version }}
      app.kubernetes.io/managed-by: quarkus
    name: ${{ values.componentId }}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app.kubernetes.io/name: ${{ values.componentId }}
        app.kubernetes.io/version: ${{ values.version }}
    template:
      metadata:
        annotations:
          app.quarkus.io/quarkus-version: 3.18.3
          app.quarkus.io/commit-id: c708e59c9760a922c4a2b1a73ee3b21d1ffc6f4a
          app.quarkus.io/vcs-uri: https://github.com/iocanel/${{ values.componentId }}.git
          app.quarkus.io/build-timestamp: 2025-04-08 - 12:38:31 +0000
        labels:
          app.kubernetes.io/managed-by: quarkus
          app.kubernetes.io/name: ${{ values.componentId }}
          app.kubernetes.io/version: ${{ values.version }}
      spec:
        containers:
          - env:
              - name: KUBERNETES_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
            image: {{ .Values.app.image }}
            imagePullPolicy: Always
            name: ${{ values.componentId }}
            ports:
              - containerPort: {{ .Values.app.ports.http }}
                name: http
                protocol: TCP
