 |
  
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      app.quarkus.io/quarkus-version: 3.18.3
      app.quarkus.io/commit-id: c708e59c9760a922c4a2b1a73ee3b21d1ffc6f4a
      app.quarkus.io/vcs-uri: https://github.com/iocanel/hello-backstage.git
      app.quarkus.io/build-timestamp: 2025-04-08 - 12:38:31 +0000
    labels:
      app.kubernetes.io/name: hello-backstage
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/managed-by: quarkus
    name: hello-backstage
  spec:
    replicas: 1
    selector:
      matchLabels:
        app.kubernetes.io/name: hello-backstage
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    template:
      metadata:
        annotations:
          app.quarkus.io/quarkus-version: 3.18.3
          app.quarkus.io/commit-id: c708e59c9760a922c4a2b1a73ee3b21d1ffc6f4a
          app.quarkus.io/vcs-uri: https://github.com/iocanel/hello-backstage.git
          app.quarkus.io/build-timestamp: 2025-04-08 - 12:38:31 +0000
        labels:
          app.kubernetes.io/managed-by: quarkus
          app.kubernetes.io/name: hello-backstage
          app.kubernetes.io/version: 1.0.0-SNAPSHOT
      spec:
        containers:
          - env:
              - name: KUBERNETES_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
            image: {{ .Values.app.image }}
            imagePullPolicy: Always
            name: hello-backstage
            ports:
              - containerPort: {{ .Values.app.ports.http }}
                name: http
                protocol: TCP
