---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.22.0
    app.quarkus.io/commit-id: 5dcb6a0c054b1897bd00fe573de70777846cc5ca
    app.quarkus.io/vcs-uri: https://github.com/iocanel/hello-backstage.git
    app.quarkus.io/build-timestamp: 2025-05-01 - 10:56:55 +0000
  labels:
    app.kubernetes.io/name: hello-backstage
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: hello-backstage
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.app.ports.http }}
  selector:
    app.kubernetes.io/name: hello-backstage
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
